git log --pretty=format:"%ad:%an:%d:%B" # Date : Title : ...
        --date=short          # Display only a short date
        --reverse             # Display latest last
        --since=2.months.ago  # Display commits only since ...
        --author=Linus        # Display only commits from one author
        --all
